#!/bin/bash

[[ ! -f bin/floatsums ]] && bash compile

T=1000

> results/seq.csv
> results/pair.csv
> results/blockseq.csv
> results/blockpair.csv
> results/tmp

# 1000000 10000000 10000000 

MODEL=models/3bin.spc

for N in 100 1000 10000 100000  ; do
	./bin/floatsums -N $N -T $T -m $MODEL -v -f results/tmp
	cat results/tmp >> results/seq.csv
	./bin/floatsums -N $N -T $T -m $MODEL -p -v -f results/tmp
	cat results/tmp >> results/pair.csv
	./bin/floatsums -N $N -T $T -m $MODEL -v -b -f results/tmp
	cat results/tmp >> results/blockseq.csv
	./bin/floatsums -N $N -T $T -m $MODEL -v -p -b -f results/tmp
	cat results/tmp >> results/blockpair.csv
done